version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk-bionic # Use a Docker image with Java 17

    working_directory: ~/my-app

    steps:
      - checkout # Checkout your source code from the repository

      - run:
          name: Build and Test
          command: |
            ./mvnw clean install -DskipTests=false

      - run:
          name: Run Tests
          command: |
            ./mvnw test


